### ISSUE TITLE
ENV Variable Examples

### ISSUE THREAD

**Issue by benyanke** [faktiva/php-redis-admin#18]
The readme says " You can use ENV variables to override any configuration directive of PHP Redis Admin.  Moreover".

Could you provide some examples? What env examples should be set to override server hostname/user/pw/port, for example? Or the login password?

**Comment by drAlberT** [comment]
Hi,
    it is mentioned in the "**Docker**" paragraph, you can find the official **_docker run_** documentation in the "[Set environment variables](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e-env-env-file)" section.

You can always [override PHPREDMIN_ configs by means of defining it in the ENV](https://github.com/faktiva/php-redis-admin/blob/master/src/libraries/app.php#L59) (in the shell, in docker, etc .. ) ..

**Comment by benyanke** [comment]
I guess you may have misunderstood the question. What are the actual names of the vars to be set to change specific configs?

**Comment by drAlberT** [comment]
Unfortunately the original project has a quite poor implementation of modern PHP techniques, so .. digging into the code, you can see that it is setting in $app->config everything found in the ENV and starting with `PHPREDMIN_` ... you can try to argue what are the valid config options searching for "config[" in the code ;(

Sorry but I have no time to rewrite the main code, it should be done :(
